
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LTE = 23;
  public static final int EQUALS = 17;
  public static final int _Q = 22;
  public static final int LPAREN = 5;
  public static final int INT = 20;
  public static final int MINUS = 4;
  public static final int REF = 21;
  public static final int RPAREN = 6;
  public static final int NOT = 31;
  public static final int LCURL = 7;
  public static final int SEMICOLON = 16;
  public static final int AND = 29;
  public static final int LT = 27;
  public static final int NIL = 36;
  public static final int INTCONST = 18;
  public static final int OR = 30;
  public static final int COMMA = 10;
  public static final int PLUS = 3;
  public static final int IF = 32;
  public static final int DOT = 2;
  public static final int EOF = 0;
  public static final int U_MINUS = 14;
  public static final int RETURN = 15;
  public static final int error = 1;
  public static final int MUTABLE = 35;
  public static final int IDENT = 19;
  public static final int EQ = 25;
  public static final int GTE = 24;
  public static final int LBRACK = 11;
  public static final int RCURL = 8;
  public static final int TIMES = 13;
  public static final int ELSE = 33;
  public static final int RBRACK = 12;
  public static final int WHILE = 34;
  public static final int GT = 28;
  public static final int PRINT = 9;
  public static final int NOTEQ = 26;
  public static final int FREE = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DOT",
  "PLUS",
  "MINUS",
  "LPAREN",
  "RPAREN",
  "LCURL",
  "RCURL",
  "PRINT",
  "COMMA",
  "LBRACK",
  "RBRACK",
  "TIMES",
  "U_MINUS",
  "RETURN",
  "SEMICOLON",
  "EQUALS",
  "INTCONST",
  "IDENT",
  "INT",
  "REF",
  "_Q",
  "LTE",
  "GTE",
  "EQ",
  "NOTEQ",
  "LT",
  "GT",
  "AND",
  "OR",
  "NOT",
  "IF",
  "ELSE",
  "WHILE",
  "MUTABLE",
  "NIL",
  "FREE"
  };
}

